#!/usr/bin/env php
<?php

$local_config = dirname( dirname( dirname( __FILE__ ) ) ) . '/wp-local-config.php';
require_once( $local_config );

// create temporary config file with connection options
$config_file = dirname( __FILE__ ) . '/.my.cnf';
touch($config_file);
chmod($config_file, 0600);
file_put_contents($config_file, "[client]
  host = " . DB_HOST . "
  user = " . DB_USER . "
  password = " . DB_PASSWORD . "
  skip-extended-insert
");

$backup_file = dirname( __FILE__ ) . '/var/database.sql';
$mysqldump = sprintf('mysqldump --defaults-file=%s %s > "%s"',
  $config_file, DB_NAME, $backup_file);

echo "backing up database to file: $backup_file\n";
system($mysqldump);

// cleanup config file
unlink($config_file);
